### ISSUE TITLE
Create Json file 

### ISSUE THREAD

**Issue by maulik225** [maulik225/69fitness#1]
**create json file for everyday workout.
Here is the example of json object.**

```
[
    {
    "title": "Warmup",
    "imgLink":"https://cdn.pixabay.com/photo/2014/03/24/13/40/dumbbells-293955_960_720.png",
    "exercises": [
      "Pushups",
      "Squats",
      "Joint movements"]
    },
    {
    "title": "Chest Press",
    "videoLink": "https://www.youtube.com/watch?v=vcBig73ojpE&ab_channel=JeffNippard",
    "exercises": ["4 sets of 10 reps"]
    },
    {
    "title": "Incliine Bench Press",
    "videoLink": "https://www.youtube.com/watch?v=SrqOu55lrYU&ab_channel=ScottHermanFitness",
    "exercises": ["4 sets of 10 reps"]
    }
]
```

Create monday.json,tuesday.json .... so on .
I am attaching content file.
Feel free to ask any questions.
Thank you
---------------------------------------------------------------------------------------
[content.txt](https://github.com/maulik225/69fitness/files/8741920/content.txt)

**Comment by uemrey0** [comment]
Hi, I send a pull request about it

**Comment by maulik225** [comment]
> Hi, I send a pull request about it

**Comment by maulik225** [comment]
> Hi, I send a pull request about it

Great work !! , PR has been merged. Thank you.
